# Generated by Django 5.1.7 on 2025-05-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nashr_yili', models.IntegerField()),
                ('nashr_soni', models.IntegerField()),
                ('num', models.CharField(max_length=100)),
                ('num1', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='ArxivArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nashr_yili', models.IntegerField()),
                ('nashr_soni', models.IntegerField()),
                ('num', models.CharField(max_length=100)),
                ('num1', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
                ('archived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TastiqlanganMaqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Maqola mavzusi')),
                ('muallif', models.CharField(max_length=100, verbose_name='Muallif')),
                ('matn', models.TextField(default='Matn mavjud emas', verbose_name='Maqola matni')),
                ('kategoriya', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('kalit_sozlar', models.CharField(blank=True, max_length=200, verbose_name='Kalit so‘zlar')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='tasdiqlangan_rasmlar/')),
                ('fayl', models.FileField(blank=True, null=True, upload_to='tasdiqlangan_fayllar/')),
                ('yaratilgan_sana', models.DateTimeField()),
            ],
        ),
    ]
