# Generated by Django 5.1.7 on 2025-05-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextexbaza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tastiqlanganmaqola',
            name='rasm',
        ),
        migrations.AddField(
            model_name='tastiqlanganmaqola',
            name='telefon_raqam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bog‘lanish uchun telefon raqam'),
        ),
    ]
