# Generated by Django 5.1.7 on 2025-06-02 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Elektron pochta')),
                ('message', models.TextField(null=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Maqola mavzusi')),
                ('muallif', models.CharField(max_length=100, verbose_name='Muallif')),
                ('matn', models.TextField(verbose_name='Maqola anotatsiyasi')),
                ('kategoriya', models.CharField(choices=[('texnologiya', 'Texnologiya'), ('talim', "Ta'lim"), ('tibbiyot', 'Tibbiyot'), ('iqtisod', 'Iqtisodiyot'), ('boshqa', 'Boshqalar')], max_length=100, verbose_name='Kategoriya')),
                ('kalit_sozlar', models.CharField(blank=True, max_length=200, verbose_name='Kalit so‘zlar')),
                ('telefon_raqam', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bog‘lanish uchun telefon raqam')),
                ('fayl', models.FileField(blank=True, null=True, upload_to='maqola_fayllar/', verbose_name='Maqola fayl')),
                ('yaratilgan_sana', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('status', models.CharField(choices=[('tekshirilmoqda', 'Tekshirilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='tekshirilmoqda', max_length=20, verbose_name='Holat')),
                ('foydalanuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuklovchi foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='MaqolaYuborishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuborilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('holat', models.BooleanField(blank=True, null=True)),
                ('javob_berilgan', models.BooleanField(default=False)),
                ('kimga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boglanish.maqola')),
            ],
        ),
        migrations.CreateModel(
            name='NewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
