# Generated by Django 5.1.7 on 2025-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boglanish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolayuborishlog',
            name='kimga',
            field=models.CharField(max_length=100),
        ),
    ]
