# Generated by Django 5.1.7 on 2025-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('taqrizchi_inf1', "Jo'rayev Adhamjon Informatika Taqrizchisi 1-raqamli"), ('taqrizchi_inf2', 'Sobirov Azizber Informatika Taqrizchisi 2-raqamli'), ('taqrizchi_inf3', 'Xasanov Saredor Informatika Taqrizchisi 3-raqamli'), ('taqrizchi_iq1', 'Ergasheva Halima Iqtisod Taqrizchisi 1-raqamli'), ('taqrizchi_iq2', 'Muhammadaliyev Zuhriddin Iqtisod Taqrizchisi 2-raqamli'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
